# This is a basic workflow to help you get started with Actions

name: pipeline

# Controls when the action will run. 
on:
  # Triggers the workflow on push events
  push:
    branches: [ main, qa, integration ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # set env variables depending on environment
  configure: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: load env vars
        uses: falti/dotenv-action@v0.2.5
        with: 
          log-variables: true
      - name: load env vars for prod
        uses: falti/dotenv-action@v0.2.5
        if: ${{ github.ref == 'refs/heads/main' }}
        with: 
          path: "./.dev.env"
          log-variables: true
      
      - name: load env vars for qa
        uses: falti/dotenv-action@v0.2.5
        if: ${{ github.ref == 'refs/heads/qa' }}
        with: 
          path: .qa.env
          log-variables: true
          
      - name: load env vars for dev
        uses: falti/dotenv-action@v0.2.5
        if: ${{ github.ref == 'refs/heads/integration' }}
        with: 
          path: .dev.env
          log-variables: true
      - name: echo
        run: echo "$GITHUB_REF"
